package org.indelible.counter.theme
import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006496)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFCCE5FF)
val md_theme_light_onPrimaryContainer = Color(0xFF001E31)
val md_theme_light_secondary = Color(0xFF006687)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFC1E8FF)
val md_theme_light_onSecondaryContainer = Color(0xFF001E2B)
val md_theme_light_tertiary = Color(0xFF7C5800)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFFFDEA7)
val md_theme_light_onTertiaryContainer = Color(0xFF271900)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFCFF)
val md_theme_light_onBackground = Color(0xFF1A1C1E)
val md_theme_light_surface = Color(0xFFFCFCFF)
val md_theme_light_onSurface = Color(0xFF1A1C1E)
val md_theme_light_surfaceVariant = Color(0xFFDEE3EA)
val md_theme_light_onSurfaceVariant = Color(0xFF42474E)
val md_theme_light_outline = Color(0xFF72787E)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F4)
val md_theme_light_inverseSurface = Color(0xFF2F3133)
val md_theme_light_inversePrimary = Color(0xFF91CDFF)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006496)
val md_theme_light_outlineVariant = Color(0xFFC2C7CE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF91CDFF)
val md_theme_dark_onPrimary = Color(0xFF003350)
val md_theme_dark_primaryContainer = Color(0xFF004B72)
val md_theme_dark_onPrimaryContainer = Color(0xFFCCE5FF)
val md_theme_dark_secondary = Color(0xFF74D1FF)
val md_theme_dark_onSecondary = Color(0xFF003548)
val md_theme_dark_secondaryContainer = Color(0xFF004D67)
val md_theme_dark_onSecondaryContainer = Color(0xFFC1E8FF)
val md_theme_dark_tertiary = Color(0xFFF7BD48)
val md_theme_dark_onTertiary = Color(0xFF412D00)
val md_theme_dark_tertiaryContainer = Color(0xFF5E4200)
val md_theme_dark_onTertiaryContainer = Color(0xFFFFDEA7)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C1E)
val md_theme_dark_onBackground = Color(0xFFE2E2E5)
val md_theme_dark_surface = Color(0xFF1A1C1E)
val md_theme_dark_onSurface = Color(0xFFE2E2E5)
val md_theme_dark_surfaceVariant = Color(0xFF42474E)
val md_theme_dark_onSurfaceVariant = Color(0xFFC2C7CE)
val md_theme_dark_outline = Color(0xFF8C9198)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C1E)
val md_theme_dark_inverseSurface = Color(0xFFE2E2E5)
val md_theme_dark_inversePrimary = Color(0xFF006496)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF91CDFF)
val md_theme_dark_outlineVariant = Color(0xFF42474E)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF33658A)
val Hunyadiyellow = Color(0xFFF6AE2D)
val Pantoneorange = Color(0xFFF26419)
val light_Hunyadiyellow = Color(0xFF805600)
val light_onHunyadiyellow = Color(0xFFFFFFFF)
val light_HunyadiyellowContainer = Color(0xFFFFDDB0)
val light_onHunyadiyellowContainer = Color(0xFF281800)
val dark_Hunyadiyellow = Color(0xFFFFBA46)
val dark_onHunyadiyellow = Color(0xFF442C00)
val dark_HunyadiyellowContainer = Color(0xFF614000)
val dark_onHunyadiyellowContainer = Color(0xFFFFDDB0)
val light_Pantoneorange = Color(0xFFA43D00)
val light_onPantoneorange = Color(0xFFFFFFFF)
val light_PantoneorangeContainer = Color(0xFFFFDBCD)
val light_onPantoneorangeContainer = Color(0xFF360F00)
val dark_Pantoneorange = Color(0xFFFFB597)
val dark_onPantoneorange = Color(0xFF591D00)
val dark_PantoneorangeContainer = Color(0xFF7D2D00)
val dark_onPantoneorangeContainer = Color(0xFFFFDBCD)

val darkSpringGreen = Color(0xFF04724D)
val jasmine = Color(0xFFFFD972)
val carolina_blue = Color(0xFF86BBD8)

val Pink200 = Color(0xFFFCE8E5)
val Red80 = Color(0xFFD93025)
val Cantaloupe200 = Color(0xFFFEEEE3)
val Orange80 = Color(0xFFE87109)
val Purple200 = Color(0xFFF3E8FD)
val Purple100 = Color(0xFF9334E6)
val Flora200 = Color(0xFFE6F4EA)
val Flora80 = Color(0xFF1C8E3E)
val Blue200 = Color(0xFFE7F0FE)
val Blue80 = Color(0xFF1B73E8)


val colorList = listOf(darkSpringGreen, Hunyadiyellow, md_theme_light_primary)